project:
  type: website

website:
  title: "Stefan's Blog"
  description: Things I learned or want to learn.
  repo-url: https://github.com/stefanbschneider/blog
  repo-actions: [issue]
  google-analytics: G-RDWKTYTDBL
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      # - icon: house
      #   href: https://stefanbschneider.github.io/
      - icon: github
        href: https://github.com/stefanbschneider/
format:
  html:
    theme: cosmo
    css: styles.css



