project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      # - icon: house
      #   href: https://stefanbschneider.github.io/
      - icon: github
        href: https://github.com/stefanbschneider/
format:
  html:
    theme: cosmo
    css: styles.css



